// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// C_threepoint
SEXP C_threepoint(SEXP dat);
RcppExport SEXP _bayou_C_threepoint(SEXP datSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type dat(datSEXP);
    rcpp_result_gen = Rcpp::wrap(C_threepoint(dat));
    return rcpp_result_gen;
END_RCPP
}
// C_transf_branch_lengths
SEXP C_transf_branch_lengths(SEXP dat, int model, NumericVector y, double alpha);
RcppExport SEXP _bayou_C_transf_branch_lengths(SEXP datSEXP, SEXP modelSEXP, SEXP ySEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type dat(datSEXP);
    Rcpp::traits::input_parameter< int >::type model(modelSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(C_transf_branch_lengths(dat, model, y, alpha));
    return rcpp_result_gen;
END_RCPP
}
// C_weightmatrix
SEXP C_weightmatrix(SEXP dat, SEXP parameters);
RcppExport SEXP _bayou_C_weightmatrix(SEXP datSEXP, SEXP parametersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type dat(datSEXP);
    Rcpp::traits::input_parameter< SEXP >::type parameters(parametersSEXP);
    rcpp_result_gen = Rcpp::wrap(C_weightmatrix(dat, parameters));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP bm_direct2(SEXP, SEXP);
RcppExport SEXP cache_descendants(SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_bayou_C_threepoint", (DL_FUNC) &_bayou_C_threepoint, 1},
    {"_bayou_C_transf_branch_lengths", (DL_FUNC) &_bayou_C_transf_branch_lengths, 4},
    {"_bayou_C_weightmatrix", (DL_FUNC) &_bayou_C_weightmatrix, 2},
    {"bm_direct2",                     (DL_FUNC) &bm_direct2,                     2},
    {"cache_descendants",              (DL_FUNC) &cache_descendants,              2},
    {NULL, NULL, 0}
};

RcppExport void R_init_bayou(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
