# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_threepoint <- function(dat) {
    .Call('_bayou_C_threepoint', PACKAGE = 'bayou', dat)
}

C_transf_branch_lengths <- function(dat, model, y, alpha) {
    .Call('_bayou_C_transf_branch_lengths', PACKAGE = 'bayou', dat, model, y, alpha)
}

C_weightmatrix <- function(dat, parameters) {
    .Call('_bayou_C_weightmatrix', PACKAGE = 'bayou', dat, parameters)
}

